cluster.name: "docker-clsuter"
network.host: 0.0.0.0

discovery.zen.minimum_master_nodes: 1
discovery.type: single-node

xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.ml.enabled: false
xpack.watcher.enabled: false

http.cors.enabled: true
http.cors.allow-origin: "*"
