FROM mcr.microsoft.com/dotnet/core/sdk:3.1.101 as build

COPY . .

RUN mkdir /nuget
RUN dotnet publish -c Release -o /app sample/SampleApp2/SampleApp2.csproj

FROM baseimage:3.1
COPY --from=build /app /app

EXPOSE 80

WORKDIR /app

ENTRYPOINT ["dotnet", "SampleApp2.dll"]
