FROM mcr.microsoft.com/dotnet/core/sdk:2.2.207 as build

COPY . .

RUN mkdir /nuget
RUN dotnet publish -c Release -o /app sample/SampleApp2/SampleApp2.csproj

FROM baseimage:2.2
COPY --from=build /app /app

EXPOSE 80

WORKDIR /app

ENTRYPOINT ["dotnet", "SampleApp2.dll"]
