{
 "title": "SampleDashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "services",
    "query": "query_result(count(samplehc) by (service))"
   },
   {
    "name": "dependencies",
    "query": "query_result(count(samplehc) by (dependency))"
   }
  ]
 },
 "panels": [
  {
   "title": "HealthCheck",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(samplehc{dependency=~\"$dependencies\",service=~\"$services\"}) by(service,dependency) < 1",
     "legendFormat": "{{service}} - {{dependency}}"
    }
   ]
  },
  {
   "title": "Expensive HTTP Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sort_desc(topk(100, max by(controller, action) (samplehttp{quantile=\"0.99\",service=~\"$services\"})))"
    }
   ]
  },
  {
   "title": "Http Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "samplehttp{service=~\"$services\",statusCode!=\"200\",quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "Expensive Masstransit Executions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sort_desc(topk(100, max by(service, messageType) (samplemasstransit{quantile=\"0.99\",service=~\"$services\"})))"
    }
   ]
  },
  {
   "title": "Masstransit Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "samplemasstransit{quantile=\"0.99\",service=~\"$services\",success=\"False\"}"
    }
   ]
  },
  {
   "title": "Expensive EFCore Executions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sort_desc(topk(100, max by(service, commandText) (sampleef{quantile=\"0.99\",service=~\"$services\"})))"
    }
   ]
  },
  {
   "title": "EFCore Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sampleef{quantile=\"0.99\",service=~\"$services\",success=\"False\"}"
    }
   ]
  },
  {
   "title": "Expensive Custom Executions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sort_desc(topk(100, max by(service, activityName) (samplecustomtracking{quantile=\"0.99\",service=~\"$services\"})))"
    }
   ]
  },
  {
   "title": "Custom Execution Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "samplecustomtracking{quantile=\"0.99\",service=~\"$services\",success=\"False\"}"
    }
   ]
  }
 ]
}